ARG JDKVER=17.0.6_10
FROM alpine:3.17.2 AS build-env
ARG TDVERSION=3.0.2.5
ARG TDVERSION_FULL=ver-${TDVERSION}

WORKDIR /tdengine

RUN apk add --no-cache alpine-sdk gcc musl-dev git cmake bash
RUN apk add --no-cache jansson-dev snappy-dev xz-dev libzip-dev zlib-dev

RUN git clone --depth=1 -b ${TDVERSION_FULL} https://github.com/taosdata/TDengine .
RUN git submodule update --init --recursive
RUN ./build.sh


FROM eclipse-temurin:${JDKVER}-jdk-alpine
ARG TDVERSION
ADD taos.cfg /etc/taos/taos.cfg
COPY --from=build-env /tdengine/debug/build/lib/libtaos.so.${TDVERSION} /usr/lib/libtaos.so.${TDVERSION}
RUN ln -s /usr/lib/libtaos.so.${TDVERSION} /usr/lib/libtaos.so
RUN ln -s /usr/lib/libtaos.so.${TDVERSION} /usr/lib/libtaos.so.1