name: Sync tdengine latest version

on:
  schedule:
    - cron: '10 7 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/taosdata/TDengine/releases/latest" | jq -r '.tag_name' | sed -e 's/ver-//g')
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Check if tag changed
        id: check_tag_change
        run: |
          LAST_TAG=$(cat LATEST_VERSION)
          echo "Last tag: $LAST_TAG"
          echo "tag_changed=$(test $LAST_TAG != ${{ steps.get_latest_tag.outputs.tag }} && echo true || echo false)" >> $GITHUB_OUTPUT
      
      - name: Build on Tag Change
        if: steps.check_tag_change.outputs.tag_changed == 'true'
        run: |
          echo "${{ steps.get_latest_tag.outputs.tag }}" > LATEST_VERSION
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "feat: bump version@${{ steps.get_latest_tag.outputs.tag }}"
          git tag ${{ steps.get_latest_tag.outputs.tag }}

      - name: Push changes
        if: steps.check_tag_change.outputs.tag_changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        if: steps.check_tag_change.outputs.tag_changed == 'true'
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: ${{ github.head_ref }}
          tags: true

      - name: Trigger docker build
        if: steps.check_tag_change.outputs.tag_changed == 'true'
        run: |
          REPO_OWNER=enix223
          REPO_NAME=tdengine-openjdk-client
          TRIGGER_WORKFLOW_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.REPO_SCOPED_TOKEN }}" "https://api.github.com/repos/enix223/tdengine-openjdk-client/actions/workflows" | jq -r '.workflows[1].id')

          response=$(curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SCOPED_TOKEN }}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$TRIGGER_WORKFLOW_ID/dispatches" \
            -d '{"ref":"main"}')
          echo $response
